name: Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: nofilter
          fail_level: any
  verify-abi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/setup-gradle@v5
      - name: Check ABI
        run: ./gradlew checkAbi

  verify-libs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v5

      - name: Execute Gradle build
        run: ./gradlew detekt

      - name: Build leviathan
        run: ./gradlew leviathan:assemble

      - name: Build leviathan-compose
        run: ./gradlew leviathan-compose:assemble
